name: subtrack
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.5.0
  uuid: ^4.5.2
  google_fonts: ^6.3.2
  font_awesome_flutter: ^10.9.1
  smooth_corner: ^1.1.1
  google_sign_in: ^6.2.1
  svg_icon: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/google.png